name: CI

on:
  - pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build-and-deploy
    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v2

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Build the project using Gradle
      - name: Build and test
        working-directory: rentalService
        run: |
          export SHELL=/bin/bash
          ./gradlew build

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t rental-service:latest -f rentalService/Dockerfile .

      # Step 5: Run the Docker container
      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 rental-service:latest

